<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divusercentrics-root-DOUGLAS-255</name>
   <tag></tag>
   <elementGuidId>7f180c08-ed40-4eef-84ca-250893a71c68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#usercentrics-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='usercentrics-root']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2aaad1fa-5d99-449a-854a-31ccfd729f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usercentrics-root</value>
      <webElementGuid>59bf4e65-1108-45ba-abc4-bdb6a68a9711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-created-at</name>
      <type>Main</type>
      <value>1724190096653</value>
      <webElementGuid>7f96ff2d-8b1d-4a93-850c-e394caf78e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usercentrics-root&quot;)</value>
      <webElementGuid>faabb99e-2a16-4d8c-9d71-56b6fc161b32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='usercentrics-root']</value>
      <webElementGuid>a8fc4521-1c4f-4dd9-9b25-92f5186d8822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>83bc1b64-9316-4efd-9013-0bb84d637647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'usercentrics-root']</value>
      <webElementGuid>6e5bef41-2e7b-46a3-84d4-8967e5ede63d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
